In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('Comedy.csv')

In [4]:
df.head()

,name,year,movie_rated,run_length,genres,release_date,rating,num_raters,num_reviews,review_url
0,Guardians of the Galaxy,2014,PG-13,2h 1min,Comedy;,1 August 2014 (USA),8.0,1017578,1390,https://www.imdb.com/title/tt2015381/reviews/_...
1,Back to the Future,1985,PG,1h 56min,Comedy;,3 July 1985 (USA),8.5,1015437,1178,https://www.imdb.com/title/tt0088763/reviews/_...
2,Finding Nemo,2003,G,1h 40min,Comedy;,30 May 2003 (USA),8.1,922237,968,https://www.imdb.com/title/tt0266543/reviews/_...
3,Up,2009,PG,1h 36min,Comedy;,29 May 2009 (USA),8.2,905205,891,https://www.imdb.com/title/tt1049413/reviews/_...
4,The Truman Show,1998,PG,1h 43min,Comedy;,5 June 1998 (USA),8.1,901368,1152,https://www.imdb.com/title/tt0120382/reviews/_...

In [16]:
df = df.drop(columns = ["review_url"])

In [17]:
df['features'] = df['genres'] + ' ' + df['year'].astype(str) + ' ' + df['movie_rated']

In [18]:
df.head()

,name,year,movie_rated,run_length,genres,release_date,rating,num_raters,num_reviews,features
0,Guardians of the Galaxy,2014,PG-13,2h 1min,Comedy;,1 August 2014 (USA),8.0,1017578,1390,Comedy; 2014 PG-13
1,Back to the Future,1985,PG,1h 56min,Comedy;,3 July 1985 (USA),8.5,1015437,1178,Comedy; 1985 PG
2,Finding Nemo,2003,G,1h 40min,Comedy;,30 May 2003 (USA),8.1,922237,968,Comedy; 2003 G
3,Up,2009,PG,1h 36min,Comedy;,29 May 2009 (USA),8.2,905205,891,Comedy; 2009 PG
4,The Truman Show,1998,PG,1h 43min,Comedy;,5 June 1998 (USA),8.1,901368,1152,Comedy; 1998 PG

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [22]:
tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(df['features'])

In [24]:
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)